spring.application.name=notification-service
server.port=8083

# Conexão RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# BOAS PRÁTICAS: Se o código lançar qualquer exceção, REJEITA a mensagem (vai direto para a DLQ)
spring.rabbitmq.listener.simple.default-requeue-rejected=false