version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fintech-rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação dos microsserviços
      - "15672:15672" # Porta do painel visual do RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
