spring.application.name=transaction-service

# Porta onde este microsserviço vai rodar
server.port=8081

# Configuração do MongoDB (Substitua pelos seus dados do Atlas)

spring.mongodb.uri=mongodb+srv://rodrigodeoliveirasa_db_user:ieMR1CezZSpisBvZ@cluster0.eku2hfd.mongodb.net/fintech_db?retryWrites=true&w=majority

# Configurações do RabbitMQ Local (Docker)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin