spring.application.name=category-service

spring.application.name=category-service
server.port=8082

# Conexão com o RabbitMQ Local (Docker)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin